# -*- coding: utf-8 -*-
"""uber analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0IQ4CAIm4eAhewbjF2EZw-lA3lGOcMj
"""

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("uber.csv")

df=pd.DataFrame(data)

df.notnull().sum()

df=df.dropna(axis=0)

df.notnull().sum()

print(df.columns)

df.head()

df['Year'] = pd.to_datetime(df['pickup_datetime']).dt.year

df.Year

ypoints=df.groupby('Year')['fare_amount'].mean()
ypoints

plt.plot(ypoints,marker="v",color='green')
plt.xlabel("YEAR",color='red')
plt.ylabel("FARE AMOUNT",color='red')

xpoints=df.groupby('Year')['passenger_count'].sum()
xpoints

plt.plot(xpoints,color='orange')
plt.xlabel('YEAR',color='red')
plt.ylabel('PASSENGER COUNT',color='red')

plt.scatter(df.pickup_latitude,df.dropoff_latitude, c='blue', s=50, alpha=0.2, linewidths=2, edgecolors='red')
plt.title("sactter plot")
plt.xlabel("Pickup latitude")
plt.ylabel("Dropoff latitude")

if(df.duplicated().all()==False):
  print("no duplicates in rows")

df1=pd.DataFrame(df.drop_duplicates('pickup_latitude'))

df.notnull().sum()==df1.notnull().sum()